cifra_rezervor__bordura_exterioara__grosime = 'crez$bordura$ext$grosime'
cifra_rezervor__bordura_interioara__grosime = 'crez$bordura$int$grosime'
cifra_rezervor__bordura_exterioara__culoare = 'crez$bordura$ext$culoare'
cifra_rezervor__bordura_interioara__culoare = 'crez$bordura$int$culoare'
cifra_rezervor__casuta_gol = 'crez$casuta$gol$culoare'
cifra_rezervor__casuta_plin = 'crez$casuta$plin$culoare'
cifra_rezervor__casuta_latura = 'crez$casuta$latura'